{
  "success": false,
  "return_code": 1,
  "stdout": "\ud83c\udf19 Moon Dev: Initialized SqueezeValidation Strategy \u2728\n\n",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_25_2025/backtests_package/T09_SqueezeValidation_PKG.py\", line 141, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1170, in run\n    strategy.next()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_25_2025/backtests_package/T09_SqueezeValidation_PKG.py\", line 86, in next\n    self.buy(size=size, sl=sl_price, tp=tp_price)\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 210, in buy\n    return self._broker.new_order(size, limit, stop, sl, tp)\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 713, in new_order\n    raise ValueError(\nValueError: Long orders require: SL (16597.712553337315) < LIMIT (16645.40436) < TP (16626.647446662686)\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_25_2025/backtests_package/T09_SqueezeValidation_PKG.py` failed. (See above for error)\n",
  "execution_time": 1.025792,
  "timestamp": "2025-10-25T06:18:14.344565"
}